### ISSUE TITLE
Be aware of colormatrix, transfer e colorprim

### ISSUE THREAD

**Issue by MonoS** [keijiro/FFmpegOut#13]
As i see you input a somewhat RGB24 stream, please be aware that it may require some conversion to be handled correctly as popular software and player require to set colormatrix, trasfer e colorprimaries option to achieve correct color handling if they differ from BT709 (for HD content) or BT607 (for SD content).

I've never used unity so i can't help with this, but i saw on twitter that @aras-p retwitted this project so maybe you can try to ask him to have more information.

**Comment by keijiro** [comment]
Thanks for providing the comment. Yes, I should care about it. The current implementation is too naïve about the color space.

I won't fix it because I'm going to close this project. I'll care about it when implementing an ffmpeg/libav extension for the official capturing plugin (GenericFrameRecorder).

https://github.com/Unity-Technologies/GenericFrameRecorder

**Comment by MonoS** [comment]
Thank you for your response, i didn't know you were closing your project.
