### ISSUE TITLE
What about audio?

### ISSUE THREAD

**Issue by MonoS** [keijiro/FFmpegOut#14]
Does Unity return audio?
If so maybe different option should be set for the different preset, like wav, aac, flac or ogg.

Personally i would go directly to wav as audio doesn't take that much space, but some users may like to have a compressed stream directly so to not need to reencode it (thing that is not straightforward to know)

**Comment by keijiro** [comment]
It might be a nice-to-have feature, but I expect that the official capturing plugin (GenericFrameRecorder) will cover it.

https://github.com/Unity-Technologies/GenericFrameRecorder

I'm slowly closing this project because GenericFrameRecorder is expected to be a superior solution. Although I'll continue maintenance for a while, feature requests will be rejected.

**Comment by caseypugh** [comment]
@keijiro any thoughts on when GenericFrameRecorder/MediaEncoder will actually be superior? Five months later, your library seems to outshine in quality (but I need audio for my purposes). 

https://github.com/Unity-Technologies/GenericFrameRecorder/issues/67
