### ISSUE TITLE
Please Add Support for Android and IOS

### ISSUE THREAD

**Issue by katsavav** [keijiro/FFmpegOut#24]
Please Add Support for Android and IOS

**Comment by keijiro** [comment]
- This plugin is designed for offline (non-realtime) use.
- FFmpeg is not optimized for mobile platforms.
- FFmpeg is licensed under LGPL.

These factors make this plugin quite difficult to use within practical mobile apps, and that's why I only implemented it for desktop platforms.

I'm closing this ticket, but please feel free to reopen if you have any reason/motivation to use this plugin on Android/iOS. I'll reconsider about it if there is reasonable input.
